baseurl = "https://blog.ytulsiani.com"
languageCode = "en-us"
Title = "Yash's Blog"
theme = "black-and-light"
author = "Yash Tulsiani"

[params]
    sitename = "Yash's Blog"

[[menu.main]]
    name = "About Me"
    url = "https://ytulsiani.com"
