baseurl = "www.ytulsiani.com/"
languageCode = "en-us"
Title = "Yash Tulsiani's Blog"
custom_css = "/static/css/custom.css"
theme = "hugo_theme_pickles"
[params]
  paginate = 10
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Here is my blog to share my thoughts and opinions."
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "https://www.ytulsiani.com"
    weight = 2

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
